### ISSUE TITLE
Hashtable feedback

### ISSUE THREAD

**Issue by lvreynoso** [colo6299/CS-1.2-Intro-Data-Structures#3]
Hi Wyatt! I've graded your hashtable submission and have feedback for you:

- good job passing all unit tests
- please add time complexity analysis to your code
- your code is concise and DRY, which I appreciate. However, adding comments or docstrings would improve the quality of your work.

**Comment by colo6299** [comment]
Yeah, I actually just forgot to push the docstrings. Fixed.
